name: sales_app_mvp
description: "MVP for SaleSeekr"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase - CORRECTED LATEST STABLE VERSIONS
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  firebase_ui_auth: ^1.17.0

  # State Management (Riverpod) - Corrected to latest stable
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Local Storage (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # UI & Utilities
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  responsive_framework: ^1.4.0
  scrollable_positioned_list: ^0.3.8
  sticky_headers: ^0.3.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  sliver_tools: ^0.2.12
  google_fonts: ^6.2.1
  uuid: ^4.4.0
  in_app_purchase: ^3.2.0

  # Code Generation & Others
  freezed_annotation: ^2.4.1
  auto_size_text: ^3.0.0
  grouped_list: ^6.0.0
  google_mobile_ads: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # Code Generation (Generators) - Versions compatible with above
  build_runner: ^2.4.11
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/store_logos/
    - assets/icons/
    - assets/images/category_icons/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/saleseekr_app_icon_blue.png"