// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjjpJSZg8XjMH3wn0XpU-t9cTrTiojA6Y',
    appId: '1:307296886319:web:56d47b438c9b407ca7f0da',
    messagingSenderId: '307296886319',
    projectId: 'sales-app-mvp',
    authDomain: 'sales-app-mvp.firebaseapp.com',
    storageBucket: 'sales-app-mvp.firebasestorage.app',
    measurementId: 'G-T2ZKG8E4WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWesQwEagHhGCksIsq4IFGi9jtN_ymBqE',
    appId: '1:307296886319:android:f34de661ae14ae44a7f0da',
    messagingSenderId: '307296886319',
    projectId: 'sales-app-mvp',
    storageBucket: 'sales-app-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqATu5tB1gNZkOvNx6wcmqjjoEhP1Ff4M',
    appId: '1:307296886319:ios:340b670bae86c909a7f0da',
    messagingSenderId: '307296886319',
    projectId: 'sales-app-mvp',
    storageBucket: 'sales-app-mvp.firebasestorage.app',
    androidClientId: '307296886319-6kbdmrtajj6l41lb8t7topaj6cj6r7kv.apps.googleusercontent.com',
    iosClientId: '307296886319-6qeue93ka0bb8i87r9pa8re5hrk6k8qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesAppMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqATu5tB1gNZkOvNx6wcmqjjoEhP1Ff4M',
    appId: '1:307296886319:ios:340b670bae86c909a7f0da',
    messagingSenderId: '307296886319',
    projectId: 'sales-app-mvp',
    storageBucket: 'sales-app-mvp.firebasestorage.app',
    androidClientId: '307296886319-6kbdmrtajj6l41lb8t7topaj6cj6r7kv.apps.googleusercontent.com',
    iosClientId: '307296886319-6qeue93ka0bb8i87r9pa8re5hrk6k8qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesAppMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjjpJSZg8XjMH3wn0XpU-t9cTrTiojA6Y',
    appId: '1:307296886319:web:2886ae0e648d89e6a7f0da',
    messagingSenderId: '307296886319',
    projectId: 'sales-app-mvp',
    authDomain: 'sales-app-mvp.firebaseapp.com',
    storageBucket: 'sales-app-mvp.firebasestorage.app',
    measurementId: 'G-8K16F3S43H',
  );

}